config:
  input_path: ""
  data_dimension: 1
  compression_ratio: 2.0
  apply_normalization: True
  model_name: "AE"
  model_type: "dense"
  epochs: 5
  lr: 0.001
  batch_size: 512
  early_stopping: True
  lr_scheduler: True
  early_stopping_patience: 100
  min_delta: 0
  lr_scheduler_patience: 50
  custom_norm: False
  reg_param: 0.001
  RHO: 0.05
  test_size: 0
  #number_of_columns: 24
  #latent_space_size: 12
  extra_compression: False
  intermittent_model_saving: False
  intermittent_saving_patience: 100
  mse_avg: False
  mse_sum: True
  emd: False
  l1: True
  activation_extraction: False
  deterministic_algorithm: True
  type_list: [
      "float64",
      "float64",
      "float64",
      "float64",
      "float64",
      "float64",
      "float64",
      "float64",
      "float64",
      "float64",
      "float64",
      "float64",
      "int",
      "int",
      "int",
      "int",
      "int",
      "int",
      "int",
      "float64",
      "float64",
      "float64",
      "int",
      "int",
  ]
  convert_to_blocks: False