def set_config(c):
    c.input_path = "data/example_CFD/example_CFD.npz"
    c.compression_ratio = 10.0
    # c.number_of_columns = 24
    # c.latent_space_size = 15
    c.epochs = 2
    c.early_stopping = True
    c.early_stopping_patience = 100
    c.min_delta = 0
    c.lr_scheduler = False
    c.lr_scheduler_patience = 100
    c.model_name = "Conv_AE"
    c.custom_norm = True
    c.l1 = True
    c.reg_param = 0.001
    c.RHO = 0.05
    c.lr = 0.001
    c.batch_size = 1
    c.test_size = 0
    c.data_dimension = 2
    c.apply_normalization = False
    c.extra_compression = False
    c.intermittent_model_saving = False
    c.intermittent_saving_patience = 100
